name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          wget
        
    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Install Android SDK (correct way)
      run: |
        # Создаем директорию
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        
        # Скачиваем и распаковываем
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Правильное создание структуры - КЛЮЧЕВОЙ МОМЕНТ
        mkdir -p cmdline-tools
        mv cmdline-tools cmdline-tools/latest
        
        # Настраиваем окружение
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        
        # Добавляем в PATH
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
        # Принимаем лицензии
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Устанавливаем компоненты
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        # Добавляем build-tools в PATH
        echo "$HOME/android-sdk/build-tools/33.0.0" >> $GITHUB_PATH
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
