name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-bullseye

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          openjdk-11-jdk \
          git \
          wget \
          unzip \
          zip \
          libssl-dev \
          build-essential \
          pkg-config \
          autoconf \
          automake \
          libtool

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        pip install appdirs colorama>=0.3.3 jinja2 sh toml packaging setuptools

    - name: Setup Android SDK
      run: |
        mkdir -p /opt/android-sdk
        cd /opt/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        
        export ANDROID_SDK_ROOT=/opt/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        
        yes | sdkmanager --licenses
        sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"

    - name: Build APK
      run: |
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
