name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          wget
        
    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Install Android SDK with precise setup
      run: |
        # Чистая установка Android SDK
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        
        # Скачиваем tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        rmdir cmdline-tools
        
        # Настраиваем окружение
        export ANDROID_SDK_ROOT=~/android-sdk
        export ANDROID_HOME=~/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        export PATH=$ANDROID_SDK_ROOT/build-tools/33.0.0:$PATH
        export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
        
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/33.0.0" >> $GITHUB_PATH
        
        # Принимаем лицензии
        yes | sdkmanager --licenses
        
        # Устанавливаем компоненты
        sdkmanager "build-tools;33.0.0"
        sdkmanager "platforms;android-33"
        sdkmanager "platform-tools"
        
        # Проверяем что aidl установлен
        ls -la $ANDROID_SDK_ROOT/build-tools/33.0.0/aidl*
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
