name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: beevelop/android:v2023.07.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python and Buildozer
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
