jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-33-v1.1.0  # Используй нужную версию API

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug
