name: Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create missing assets
        run: |
          # Создаем presplash если его нет
          if [ ! -f presplash.png ]; then
            python -c "
            from PIL import Image, ImageDraw
            img = Image.new('RGB', (1920, 1080), (30, 100, 200))
            d = ImageDraw.Draw(img)
            img.save('presplash.png')
            print('presplash.png created')
            "
          fi
          
          # Проверяем что icon.png существует
          if [ ! -f icon.png ]; then
            python -c "
            from PIL import Image, ImageDraw
            img = Image.new('RGB', (512, 512), (30, 100, 200))
            d = ImageDraw.Draw(img)
            img.save('icon.png')
            print('icon.png created')
            "
          fi
    
      - name: Build with Buildozer
        uses: n8marti/buildozer-action@fix-user-doesnt-exist
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
